using LazurdIT.FluentOrm.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Student.Shared
{

    [FluentTable("Courses")]
    public class CourseModel : IFluentModel
    {
        [FluentField(name: "CourseId", autoGenerated: true, isPrimary: true, allowNull: false)]
        public int Id { get; set; }

        [FluentField(name: "CourseName", allowNull: false)]
        public string Name { get; set; } = string.Empty;

        [FluentField(name: "Description", allowNull: true)]
        public string? Description { get; set; }

        public CourseModel()
        {
            Id = 0; // Default value for new entries.
        }
    }
}
