using LazurdIT.FluentOrm.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Student.Shared
{
    [FluentTable("Enrollments")]
    public class EnrollmentModel : IFluentModel
    {
        [FluentField(name: "EnrollmentId", autoGenerated: true, isPrimary: true, allowNull: false)]
        public int Id { get; set; }

        [FluentField(name: "StudentId", allowNull: false)]
        public int StudentId { get; set; }

        [FluentField(name: "CourseId", allowNull: false)]
        public int CourseId { get; set; }

        public EnrollmentModel()
        {
            Id = 0; // Default value for new entries.
        }
    }
}
